export const theme = {
  colors: {
    background: '#eff4f8',
    canvas: '#e4ecf4',
    surface: '#ffffff',
    surfaceMuted: '#f7f9fc',
    border: '#d6deea',
    borderStrong: '#c1ccda',
    text: '#10233f',
    muted: '#586b85',
    accent: '#0f766e',
    accentText: '#f7fffe',
    accentSoft: '#daf4ee',
    badge: '#d9f4ef',
    badgeText: '#0f5b55',
    successSurface: '#e8f7ef',
    successBorder: '#c7e8d3',
    successText: '#1b5e3b',
    errorSurface: '#fdeeee',
    errorBorder: '#f4caca',
    errorText: '#8d2f2b',
    warning: '#9a5b00',
    input: '#fbfcfe',
    inputBorder: '#cfd9e5',
    chip: '#ecf2f8',
    chipSelected: '#10233f',
    chipSelectedText: '#f7fbff',
    shadow: '#0f172a',
    link: '#0a5db8',
  },
  radii: {
    md: 16,
    lg: 24,
    xl: 32,
  },
} as const;
