export const theme = {
  colors: {
    background: '#f5f7fb',
    canvas: '#eef1f7',
    surface: '#ffffff',
    surfaceMuted: '#fbfcff',
    surfaceElevated: '#ffffff',
    surfaceTint: '#f7f8fc',
    border: '#e7eaf1',
    borderStrong: '#dadde8',
    text: '#1f2636',
    muted: '#7c8598',
    accent: '#ff5b57',
    accentStrong: '#f04642',
    accentText: '#ffffff',
    accentSoft: '#ffe4e2',
    accentMuted: '#fff3f2',
    badge: '#ffedec',
    badgeText: '#f04642',
    successSurface: '#fff3f2',
    successBorder: '#ffd8d6',
    successText: '#f04642',
    errorSurface: '#fff1f0',
    errorBorder: '#ffd1ce',
    errorText: '#cc3f3b',
    warning: '#cf6d00',
    input: '#ffffff',
    inputBorder: '#e2e6ef',
    chip: '#ffffff',
    chipSelected: '#ff5b57',
    chipSelectedText: '#ffffff',
    shadow: '#16213b',
    link: '#ff5b57',
    heroSurface: '#ffffff',
    heroAccent: '#ff5b57',
    heroText: '#1f2636',
  },
  radii: {
    md: 16,
    lg: 22,
    xl: 28,
  },
} as const;
